#compiler
CC = g++

#input file names
OBJS = main.c

#output file name
OBJ_NAME = main.out

COMPILER_FLAGS = -w
LINKER_FLAGS = -lSDL2 -lSDL2_image

all:
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
